library(stringr)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(tidyr)
library(ggsci)
library(ggpubr)

to_analyse = "core"

# directory should contain TSV generated by analyse_celebrimbor_simulation.py with names in format
# cgt_comp_params_x,y_err_z, where x is rare threshold, y is core threshold and z is error as decimals.
if (to_analyse == "rare")
{
  indir = "./mmseqs_results/core_0.95/"
} else if (to_analyse == "core")
{
  indir = "./mmseqs_results/rare_0.05/"
}

files <- Sys.glob(paste(indir, "*.tsv", sep = ""))

total.df <- data.frame(core_lim = c(), rare_lim = c(), error = c(), total_core = c(), total_middle = c(), total_rare = c(),
                       core_cgt_true = c(), middle_cgt_true = c(), rare_cgt_true = c(), core_freq_true = c(), middle_freq_true = c(), rare_freq_true = c(),
                       core_cgt_pred = c(), middle_cgt_pred = c(), rare_cgt_pred = c(), core_freq_pred = c(), middle_freq_pred = c(), rare_freq_pred = c())

i <- 1
for (i in 1:length(files)){
  filename <- files[i]
  df <- read.table(filename, header = 1)
  
  # extract parameters
  prefix <- str_remove(filename, indir)
  prefix <- str_remove(prefix, ".tsv")
  params <- str_split(prefix, "_")[[1]]
  lims <- params[4]
  lims <- str_split(lims, ",")[[1]]
  core_lim <- readr::parse_number(lims[2])
  rare_lim <- readr::parse_number(lims[1])
  error <- readr::parse_number(params[length(params)])
  
  df <- na.omit(df)
  
  total_core = sum(df$Pre_sim_freq_compartment == "core")
  total_middle = sum(df$Pre_sim_freq_compartment == "middle")
  total_rare = sum(df$Pre_sim_freq_compartment == "rare")
  core_cgt_true = sum(df$Pre_sim_freq_compartment == "core" & df$Post_sim_cgt_compartment == "core")
  middle_cgt_true = sum(df$Pre_sim_freq_compartment == "middle" & df$Post_sim_cgt_compartment == "middle")
  rare_cgt_true = sum(df$Pre_sim_freq_compartment == "rare" & df$Post_sim_cgt_compartment == "rare")
  core_freq_true = sum(df$Pre_sim_freq_compartment == "core" & df$Post_sim_freq_compartment == "core")
  middle_freq_true = sum(df$Pre_sim_freq_compartment == "middle" & df$Post_sim_freq_compartment == "middle")
  rare_freq_true = sum(df$Pre_sim_freq_compartment == "rare" & df$Post_sim_freq_compartment == "rare")
  core_cgt_pred = sum(df$Post_sim_cgt_compartment == "core")
  middle_cgt_pred = sum(df$Post_sim_cgt_compartment == "middle")
  rare_cgt_pred = sum(df$Post_sim_cgt_compartment == "rare")
  core_freq_pred = sum(df$Post_sim_freq_compartment == "core")
  middle_freq_pred = sum(df$Post_sim_freq_compartment == "middle")
  rare_freq_pred = sum(df$Post_sim_freq_compartment == "rare")
  
  to.append <- data.frame(core_lim = core_lim, rare_lim = rare_lim, error = error, total_core = total_core, total_middle = total_middle, total_rare = total_rare,
                         core_cgt_true = core_cgt_true, middle_cgt_true = middle_cgt_true, rare_cgt_true = rare_cgt_true, core_freq_true = core_freq_true, middle_freq_true = middle_freq_true, rare_freq_true = rare_freq_true,
                         core_cgt_pred = core_cgt_pred, middle_cgt_pred = middle_cgt_pred, rare_cgt_pred = rare_cgt_pred, core_freq_pred = core_freq_pred, middle_freq_pred = middle_freq_pred, rare_freq_pred = rare_freq_pred)
  total.df <- rbind(total.df, to.append)
}


# could try proportion?
total.df$cgt_core_true_diff <- total.df$total_core - total.df$core_cgt_true
total.df$cgt_rare_true_diff <- total.df$total_rare - total.df$rare_cgt_true
total.df$cgt_mid_true_diff <- total.df$total_middle - total.df$middle_cgt_true
total.df$pred_core_true_diff <- total.df$total_core - total.df$core_freq_true
total.df$pred_rare_true_diff <- total.df$total_rare - total.df$rare_freq_true
total.df$pred_mid_true_diff <- total.df$total_middle - total.df$middle_freq_true


mod.df <- melt(total.df, id.var = c("core_lim", "rare_lim", "error"))
subsample.df <- subset(mod.df, error == 0.05)

# generate df to print
{
  core.ori.df <- subset(mod.df, variable == "total_core")
  middle.ori.df <- subset(mod.df, variable == "total_middle")
  rare.ori.df <- subset(mod.df, variable == "total_rare")
  core.ori.df = subset(core.ori.df, select = -c(variable))
  colnames(core.ori.df) <- c("core_lim", "rare_lim", "error", "core")
  core.ori.df$type <- "ori"
  core.ori.df$tool <- "NA"
  core.ori.df$stringency <- "NA"
  core.ori.df$middle <- middle.ori.df$value
  core.ori.df$rare <- rare.ori.df$value
  
  
  core.freq.df <- subset(mod.df, variable == "core_freq_pred")
  middle.freq.df <- subset(mod.df, variable == "middle_freq_pred")
  rare.freq.df <- subset(mod.df, variable == "rare_freq_pred")
  core.freq.df = subset(core.freq.df, select = -c(variable))
  colnames(core.freq.df) <- c("core_lim", "rare_lim", "error", "core")
  core.freq.df$type <- "sim"
  core.freq.df$tool <- "freq_only"
  core.freq.df$stringency <- "NA"
  core.freq.df$middle <- middle.freq.df$value
  core.freq.df$rare <- rare.freq.df$value
  
  
  
  core.cgt.df <- subset(mod.df, variable == "core_cgt_pred")
  middle.cgt.df <- subset(mod.df, variable == "middle_cgt_pred")
  rare.cgt.df <- subset(mod.df, variable == "rare_cgt_pred")
  core.cgt.df = subset(core.cgt.df, select = -c(variable))
  colnames(core.cgt.df) <- c("core_lim", "rare_lim", "error", "core")
  core.cgt.df$type <- "sim"
  core.cgt.df$tool <- "cgt"
  core.cgt.df$stringency <- "NA"
  core.cgt.df$middle <- middle.cgt.df$value
  core.cgt.df$rare <- rare.cgt.df$value
  
  print.df <- rbind(core.ori.df, core.freq.df)
  print.df <- rbind(print.df, core.cgt.df)
}

if (to_analyse == "rare")
{
  
  subsample.df.rare <- subset(subsample.df, variable == "cgt_rare_true_diff" | variable == "pred_rare_true_diff")
  
  p <- ggplot(data=subsample.df.rare, aes(x=rare_lim, y=value, colour=variable)) + geom_point() + geom_line() + theme_light()
  p
  
  subsample.df.rare <- subset(subsample.df, variable == "total_rare" | variable == "rare_cgt_pred" | variable == "rare_freq_pred")
  
  subsample.df.rare$variable <- as.character(subsample.df.rare$variable)
  subsample.df.rare$variable[subsample.df.rare$variable == "total_rare"] <- "True Total"
  subsample.df.rare$variable[subsample.df.rare$variable == "rare_cgt_pred"] <- "CELEBRIMBOR"
  subsample.df.rare$variable[subsample.df.rare$variable == "rare_freq_pred"] <- "Unadjusted"
  subsample.df.rare$variable <- factor(subsample.df.rare$variable, levels = c("True Total", "CELEBRIMBOR", "Unadjusted"))
  
  rare_p <- ggplot(data=subsample.df.rare, aes(x=rare_lim, y=value, colour=variable)) + geom_point(size=2) + geom_line() + theme_light() + xlab("Rare threshold") + ylab("Number of rare genes") + theme(axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14), axis.title=element_text(size=20,face="bold"), strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14, face = "italic"), legend.title=element_text(size=18,face="bold"), legend.text=element_text(size=16)) + guides(colour=guide_legend(title="Method")) + scale_colour_nejm()
  rare_p
  
  subsample.df.mid1 <- subset(subsample.df, variable == "total_middle" | variable == "middle_cgt_pred" | variable == "middle_freq_pred")
  
  subsample.df.mid1$variable <- as.character(subsample.df.mid1$variable)
  subsample.df.mid1$variable[subsample.df.mid1$variable == "total_middle"] <- "True Total"
  subsample.df.mid1$variable[subsample.df.mid1$variable == "middle_cgt_pred"] <- "CELEBRIMBOR"
  subsample.df.mid1$variable[subsample.df.mid1$variable == "middle_freq_pred"] <- "Unadjusted"
  subsample.df.mid1$variable <- factor(subsample.df.mid1$variable, levels = c("True Total", "CELEBRIMBOR", "Unadjusted"))
  
  middle_p1 <- ggplot(data=subsample.df.mid1, aes(x=rare_lim, y=value, colour=variable)) + geom_point(size=2) + geom_line() + theme_light() + xlab("Rare threshold") + ylab("Number of intermediate genes") + theme(axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14), axis.title=element_text(size=20,face="bold"), strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14, face = "italic"), legend.title=element_text(size=18,face="bold"), legend.text=element_text(size=16)) + guides(colour=guide_legend(title="Method")) + scale_colour_nejm()
  middle_p1
  
  subsample.df.rare$type <-"Number of rare genes"
  subsample.df.mid1$type <-"Number of intermediate genes"
  subsample.df.all.rare <- rbind(subsample.df.rare, subsample.df.mid1)
  
  subsample.df.all.rare$type <- factor(subsample.df.all.rare$type, levels = c("Number of rare genes", "Number of intermediate genes"))
  
  all_rare_p <- ggplot(data=subsample.df.all.rare, aes(x=rare_lim, y=value, colour=variable)) + facet_grid(type~., switch = "y", scales = "free_y") + geom_point(size=2) + geom_line() + theme_light() + xlab("Rare threshold") + ylab("") + theme(axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14), axis.title=element_text(size=16,face="bold"), strip.placement = "outside", strip.background = element_blank(), strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14, colour = "black", face = "bold"), legend.title=element_text(size=18,face="bold"), legend.text=element_text(size=16)) + guides(colour=guide_legend(title="Method")) + scale_colour_nejm() + scale_y_continuous(breaks = seq(0, 100000, 2000))
  all_rare_p
  write.csv(print.df, file='mmseqs_rare.csv')
} else if (to_analyse == "core")
{
  subsample.df.core <- subset(subsample.df, variable == "cgt_core_true_diff" | variable == "pred_core_true_diff")
  
  p <- ggplot(data=subsample.df.core, aes(x=core_lim, y=value, colour=variable)) + geom_point() + geom_line() + theme_light()
  p
  
  subsample.df.core <- subset(subsample.df, variable == "total_core" | variable == "core_cgt_pred" | variable == "core_freq_pred")
  
  subsample.df.core$variable <- as.character(subsample.df.core$variable)
  subsample.df.core$variable[subsample.df.core$variable == "total_core"] <- "True Total"
  subsample.df.core$variable[subsample.df.core$variable == "core_cgt_pred"] <- "CELEBRIMBOR"
  subsample.df.core$variable[subsample.df.core$variable == "core_freq_pred"] <- "Unadjusted"
  subsample.df.core$variable <- factor(subsample.df.core$variable, levels = c("True Total", "CELEBRIMBOR", "Unadjusted"))
  
  core_p <- ggplot(data=subsample.df.core, aes(x=core_lim, y=value, colour=variable)) + geom_point(size=2) + geom_line() + theme_light() + xlab("Core threshold") + ylab("Number of core genes") + theme(axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14), axis.title=element_text(size=20,face="bold"), strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14, face = "italic"), legend.title=element_text(size=18,face="bold"), legend.text=element_text(size=16)) + guides(colour=guide_legend(title="Method")) + scale_colour_nejm()
  core_p
  
  subsample.df.mid2 <- subset(subsample.df, variable == "total_middle" | variable == "middle_cgt_pred" | variable == "middle_freq_pred")
  
  subsample.df.mid2$variable <- as.character(subsample.df.mid2$variable)
  subsample.df.mid2$variable[subsample.df.mid2$variable == "total_middle"] <- "True Total"
  subsample.df.mid2$variable[subsample.df.mid2$variable == "middle_cgt_pred"] <- "CELEBRIMBOR"
  subsample.df.mid2$variable[subsample.df.mid2$variable == "middle_freq_pred"] <- "Unadjusted"
  subsample.df.mid2$variable <- factor(subsample.df.mid2$variable, levels = c("True Total", "CELEBRIMBOR", "Unadjusted"))
  
  middle_p2 <- ggplot(data=subsample.df.mid2, aes(x=core_lim, y=value, colour=variable)) + geom_point(size=2) + geom_line() + theme_light() + xlab("Core threshold") + ylab("Number of intermediate genes") + theme(axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14), axis.title=element_text(size=20,face="bold"), strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14, face = "italic"), legend.title=element_text(size=18,face="bold"), legend.text=element_text(size=16)) + guides(colour=guide_legend(title="Method")) + scale_colour_nejm()
  middle_p2
  
  subsample.df.core$type <-"Number of core genes"
  subsample.df.mid2$type <-"Number of intermediate genes"
  subsample.df.all.core <- rbind(subsample.df.core, subsample.df.mid2)
  
  subsample.df.all.core$type <- factor(subsample.df.all.core$type, levels = c("Number of core genes", "Number of intermediate genes"))
  
  
  all_core_p <- ggplot(data=subsample.df.all.core, aes(x=core_lim, y=value, colour=variable)) + facet_grid(type~., switch = "y", scales = "free_y") + geom_point(size=2) + geom_line() + theme_light() + xlab("Core threshold") + ylab("") + theme(axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14), axis.title=element_text(size=16,face="bold"), strip.placement = "outside", strip.background = element_blank(), strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14, colour = "black", face = "bold"), legend.title=element_text(size=18,face="bold"), legend.text=element_text(size=16)) + guides(colour=guide_legend(title="Method")) + scale_colour_nejm() + scale_y_continuous(breaks = seq(0, 100000, 1000))
  all_core_p
  
  write.csv(print.df, file='mmseqs_core.csv')
}

grid.plot <- ggarrange(all_core_p, all_rare_p, align="hv", ncol = 2, common.legend = TRUE, legend="right", labels="AUTO")
grid.plot

ggsave(file="mmseqs2_simulation_figure.png", plot=grid.plot, width=14, height=7)
