library(stringr)
library(ggplot2)
library(ggpubr)
library(reshape2)
library(tidyr)
library(ggsci)
library(ggpubr)

# run to grid.plot with "core" and then full script with "rare"
to_analyse = "core"

# directory should contain TSV generated by CELEBRIMBOR with names cgt_sim_panaroo_strict_params_x,y_err_z.txt (adjusted data)
# and panaroo_sim_strict_params_x,y.tsv (unadjusted data) where x is rare threshold, y is core threshold and z is error as decimals.
if (to_analyse == "rare")
{
  indir = "./panaroo_results/core_0.95/"
} else if (to_analyse == "core")
{
  indir = "./panaroo_results/rare_0.05/"
}

files <- Sys.glob(paste(indir, "*params*", sep = ""))

total.df <- data.frame(type = c(), tool = c(), stringency = c(), core_lim = c(), rare_lim = c(), error = c(), core = c(), middle = c(), rare = c())

i <- 1
for (i in 1:length(files)){
  filename <- files[i]
  
  # extract parameters
  prefix <- str_remove(filename, indir)
  prefix <- str_remove(prefix, ".tsv")
  prefix <- str_remove(prefix, ".txt")
  params <- str_split(prefix, "_")[[1]]
  if (params[1] == "cgt")
  {
    lims <- params[6]
    error <- readr::parse_number(params[length(params)])
    type <- params[2]
    tool <- "cgt"
    stringency <- params[4]
    
    df <- read.table(filename, header = 1)
    df <- na.omit(df)
    
    core = sum(df$label == "core")
    middle = sum(df$label == "middle")
    rare = sum(df$label == "rare")
  } else if (params[1] == "panaroo")
  {
    lims <- params[5]
    error <- 0.0
    type <- params[2]
    stringency <- params[3]
    
    tool <- "panaroo"
    
    df <- read.table(filename, header = 0)
    df <- na.omit(df)
    
    colnames(df) <- c("gene", "gene2", "freq", "label")
  }
  
  lims <- str_split(lims, ",")[[1]]
  core_lim <- readr::parse_number(lims[2])
  rare_lim <- readr::parse_number(lims[1])
  
  core = sum(df$label == "core")
  middle = sum(df$label == "middle")
  rare = sum(df$label == "rare")
  
  to.append <- data.frame(type = type, tool = tool, stringency = stringency, core_lim = core_lim, rare_lim = rare_lim, error = error, core = core, middle = middle, rare = rare)
  total.df <- rbind(total.df, to.append)
}

mod.df <- melt(total.df, id.var = c("core_lim", "rare_lim", "error", "type", "tool", "stringency"))
subsample.df <- subset(mod.df, (error == 0.05 | error == 0.0))
subsample.df$type <- as.character(subsample.df$type)
subsample.df$tool <- as.character(subsample.df$tool)
subsample.df$stringency <- as.character(subsample.df$stringency)
subsample.df$type[subsample.df$type == "ori"] <- "Pre-removal"
subsample.df$type[subsample.df$type == "sim"] <- "Post-removal"
subsample.df$tool[subsample.df$tool == "cgt"] <- "CELEBRIMBOR"
subsample.df$tool[subsample.df$tool == "panaroo"] <- "Unadjusted"
subsample.df$stringency[subsample.df$stringency == "moderate"] <- "Moderate"
subsample.df$stringency[subsample.df$stringency == "strict"] <- "Strict"
subsample.df$stringency[subsample.df$stringency == "sensitive"] <- "Sensitive"
subsample.df$stringency <- factor(subsample.df$stringency, levels = c("Sensitive", "Moderate", "Strict"))
subsample.df$type <- factor(subsample.df$type, levels = c("Pre-removal", "Post-removal"))
subsample.df$tool <- factor(subsample.df$tool, levels = c("CELEBRIMBOR", "Unadjusted"))

subsample.df.true <- subset(subsample.df, type == "Pre-removal" & tool == "Unadjusted")
subsample.df.true$tool <- "True Total"
subsample.df <- subset(subsample.df, type == "Post-removal")
subsample.df <- rbind(subsample.df, subsample.df.true)
subsample.df$tool <- factor(subsample.df$tool, levels = c("True Total", "CELEBRIMBOR", "Unadjusted"))

if (to_analyse == "rare")
{
  subsample.df.rare <- subset(subsample.df, variable == "rare" & rare_lim >= 0.0 & rare_lim <= 0.3)
  subsample.df.rare$variable <-"Number of rare genes"
  
  rare_p <- ggplot(data=subsample.df.rare, aes(x=rare_lim, y=value, colour=tool)) + facet_grid(.~stringency, scales = "free_y") + geom_point(size=2, alpha=0.5) + geom_line(alpha=0.5) + theme_light() + xlab("Rare threshold") + ylab("Number of rare genes") + theme(axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14), axis.title=element_text(size=16,face="bold"), strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14), legend.title=element_text(size=18,face="bold"), legend.text=element_text(size=16)) + guides(colour=guide_legend(title="Method")) + scale_colour_nejm() + scale_y_continuous(breaks = seq(0, 100000, 2000))
  rare_p
  write.csv(total.df, file='panaroo_rare.csv')
} else if (to_analyse == "core")
{
  subsample.df.core <- subset(subsample.df, variable == "core" & core_lim >= 0.7 & core_lim <= 0.99)
  subsample.df.core$variable <-"Number of core genes"
  
  core_p <- ggplot(data=subsample.df.core, aes(x=core_lim, y=value, colour=tool)) + facet_grid(.~stringency, scales = "free_y") + geom_point(size=2, alpha=0.5) + geom_line(alpha=0.5) + theme_light() + xlab("Core threshold") + ylab("Number of core genes") + theme(axis.text.x = element_text(size = 14), axis.text.y = element_text(size = 14), axis.title=element_text(size=16,face="bold"), strip.text.x = element_text(size = 14), strip.text.y = element_text(size = 14), legend.title=element_text(size=18,face="bold"), legend.text=element_text(size=16)) + guides(colour=guide_legend(title="Method")) + scale_colour_nejm() + scale_y_continuous(breaks = seq(0, 100000, 2000))
  core_p
  write.csv(total.df, file='panaroo_core.csv')
}

grid.plot <- ggarrange(core_p, rare_p, align="hv", ncol = 1, nrow = 2, common.legend = TRUE, legend="right", labels="AUTO")
grid.plot

ggsave(file="CELEBRIMBOR_panaroo_simulation_figure.png", plot=grid.plot, width=14, height=7)